name: Sync fork with upstream
on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  workflows: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Sync upstream
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git remote add upstream https://github.com/Luminous418/LumiROM.git
          git fetch upstream
          git merge upstream/OneUI8.5 --no-edit --strategy-option=ours
          git push origin OneUI8.5
